### ISSUE TITLE
What is the status of this project (including its future plans)?

### ISSUE THREAD

**Issue by adriatic** [FSJam/fsjam-conduit#2]
Please check a brief discussion **[here](https://discord.com/channels/679514959968993311/679514959968993476/813540696094408735)** and **[here](https://discord.com/channels/679514959968993311/679514959968993476/813543234902556693)** and think whether you are still interested in developing this further.

**Comment by adriatic** [comment]
Tried to run this app on my (Windows) workstation
```
λ yarn rw dev
yarn run v1.22.5
$ c:\work\learning\redwood\fsjam-conduit\node_modules\.bin\rw dev
$ c:\work\learning\redwood\fsjam-conduit\node_modules\.bin\webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js
$ c:\work\learning\redwood\fsjam-conduit\node_modules\.bin\dev-server
api | Running at 'http://localhost:8911'
api | Watching files in 'c:\work\learning\redwood\fsjam-conduit\api\src\functions'
web | i ｢wds｣: Project is running at http://localhost:8910/
web | i ｢wds｣: webpack output is served from /
web | i ｢wds｣: Content not from webpack is served from c:\work\learning\redwood\fsjam-conduit\web
web | i ｢wds｣: 404s will fallback to /index.html
api | Done. Took 3201ms.
web | Browserslist: caniuse-lite is outdated. Please run:
web | npx browserslist@latest --update-db
```
<br>

_Note: I run the `npx browserslist@latest --update-db` already and the same warning came again_

---

The app seems unfinished as I got only this:

![image](https://user-images.githubusercontent.com/2712405/108782011-cf366900-7538-11eb-9d02-007b235db197.png)

**Comment by ajcwebdev** [comment]
I believe @Thieffen was just getting the initial models setup, I'm not sure exactly how far he got. Since this was on a much older version of Redwood it might make sense to start a refresh project and try to port over anything he's done up to this point.

I am currently busy with multiple projects right now but anyone is free to fork this or to submit contributions, but I will be unable to do any significant reviewing of PR's.

**Comment by adriatic** [comment]
Thank you @ajcwebdev for your explanation. @Thieffen , can you add anything, please? I will delay my decision to pick this project up, so that @thedavid can advise on the relative priority of this project in the context of tasks I am planning to tackle.
